### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by liambeguin**
Hi, 

`python2` is approaching end of life and most of our setup is already on `python3`.
This PR add `python3` support and was tested on a `WatlowF4T` using TCP.

test:
```sh
$ cd ChamberConnectLibrary
$ virtualenv -p python3 venv3
$ venv3/bin/pip install .
$ source venv3/bin/activate
$ python3 bin/chamberconnectlibrary-test.py WatlowF4T TCP 192.168.100.59

[ ... ]

Testing Complete
```

### CODE REVIEW

**Comment by liambeguin** [comment]
Hi @MylesMetzler any chance you had a moment to look at this?

**Comment by MylesMetzler** [comment]
Sorry for the slow response.
We use this library internally on a project that is still on using python 2.7 and is currently frozen pending a new release. After that release we can look into merging python 3 support.

I do intend to get to merging this when I am able.

**Comment by liambeguin** [comment]
okay, thanks.

**Comment by maxballenger** [comment]
Putting in another vote for Python3 compatibility. It should be possible to maintain compatibility with both. @Liambeguin do you think this is the case with your changes?

**Comment by liambeguin** [comment]
Hi @maxballenger,
I don't remember testing this with python2 but reviewing the changes, it looks like it should still work. 
Unfortunately, I can't test this right now but if you can, I'd be happy to update the merge request.

**Comment by liambeguin** [comment]
Hi @MylesMetzler any updates on this merge request? 
Has your internal project been updated since last time?

**Comment by MylesMetzler** [comment]
@Liambeguin 
@PaulNongL is looking into python3 support I am not sure where it stands. I'll ask him.

**Comment by liambeguin** [comment]
Okay, thanks for the update

**Comment by PaulNongL** [comment]
It is half way through testing on P300. I have yet to go through with F4/F4T testing. I will notify you once all tests are complete and verified working on these controllers.

**Comment by SimonL-Eno** [comment]
Hi @MylesMetzler is there any update on this merge request?
I would also like to use this in a python 3 project.

**Comment by PaulNongL** [comment]
> Hi @MylesMetzler is there any update on this merge request?
> I would also like to use this in a python 3 project.

Hello Laim: We have a separate branch for Python3. 
https://github.com/EspecNorthAmerica/ChamberConnectLibrary/tree/dev_python3

**Pull request closed without merging**
